---

- name: Install emacs
  apt:
    name: "{{ emacs_package }}"
    state: present

- name: Install extra emacs packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ emacs_extra_packages }}"
